name: Deploy Widget

on:
  workflow_dispatch: # temporary!
  push:
    tags:
      - v*

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//-latest}
    outputs:
      version: ${{ steps.tag_version.outputs.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: vars
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install --pure-lockfile

    # Build
    - name: Build Widget
      run: yarn workspace @equipment-experts/widget build

    # Deploy
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --cache-control max-age=31536000,public
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SOURCE_DIR: 'packages/widget/dist'
        DEST_DIR: 'equipment-experts-widget/v${{ needs.vars.outputs.version }}'
