name: Deploy GraphQL

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  vars:
    runs-on: ubuntu-latest
    steps:
    - id: tag_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    outputs:
      version: ${{ steps.tag_version.outputs.VERSION }}
      image: ${{ github.repository }}-graphql:${{ steps.tag_version.outputs.VERSION }}

  debug:
    runs-on: ubuntu-latest
    needs: [vars]
    steps:
      - run: echo ${{ needs.vars.outputs.image }}
      - run: echo ${{ needs.vars.outputs.version }}
      - run: echo ${{ github.repository }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        id: docker_build
        with:
          context: .
          push: true
          file: services/graphql/Dockerfile
          tags: ${{ needs.vars.outputs.image }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy:
    runs-on: ubuntu-latest
    needs: [vars, build]
    steps:
    - name: Deploy to Kubernetes
      run: npx @endeavorb2b/rancher2cli dl equipment-experts-service graphql ${{ needs.vars.outputs.image }}
      env:
        RANCHER_CLUSTERID: ${{ secrets.RANCHER_CLUSTERID_BASECMS }}
        RANCHER_TOKEN: ${{ secrets.RANCHER_TOKEN }}
        RANCHER_URL: ${{ secrets.RANCHER_URL }}
